# Generated by Django 3.2.25 on 2026-05-02 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.poll')),
            ],
            options={
                'unique_together': {('poll', 'ip_address')},
            },
        ),
    ]
